apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: standard-namespace-monitoring-recording-rules
spec:
  groups:
  - name: cpu
    rules:
    - record: container_cpu_usage_seconds_total:sum_rate5m
      expr: |-
        sum by (uid,container,pod,namespace,node) (
          label_replace(
            rate(container_cpu_usage_seconds_total{container!="", container!="POD"}[5m]) * on(pod, namespace) group_left() (kube_pod_status_phase{phase="Running"}==1)
          , "uid", "$1-$2-$3-$4-$5", "id", ".+pod([a-zA-Z0-9]{8})(?:-|_)([a-zA-Z0-9]{4})(?:-|_)([a-zA-Z0-9]{4})(?:-|_)([a-zA-Z0-9]{4})(?:-|_)([a-zA-Z0-9]{12}).+")
        )
    - record: kube_pod_container_resource_requests:cpu:running
      expr: |-
        sum by (uid,container,pod,namespace,node) (
          kube_pod_container_resource_requests{resource="cpu"} * on(pod, namespace) group_left() (kube_pod_status_phase{phase="Running"}==1)
        )
    - record: kube_pod_container_resource_limits:cpu:running
      expr: |-
        sum by (uid,container,pod,namespace,node) (
          kube_pod_container_resource_limits{resource="cpu"} * on(pod, namespace) group_left() (kube_pod_status_phase{phase="Running"}==1)
        )
    - record: container_cpu_cfs_throttling:percent
      expr: |-
        100
        /
        sum by (uid,container,pod,namespace,node) (
          label_replace(
            increase(container_cpu_cfs_periods_total{container!="", container!="POD"}[5m]) * on(pod, namespace) group_left() (kube_pod_status_phase{phase="Running"}==1)
          , "uid", "$1-$2-$3-$4-$5", "id", ".+pod([a-zA-Z0-9]{8})(?:-|_)([a-zA-Z0-9]{4})(?:-|_)([a-zA-Z0-9]{4})(?:-|_)([a-zA-Z0-9]{4})(?:-|_)([a-zA-Z0-9]{12}).+")
        )
        *
        sum by (uid,container,pod,namespace,node) (
          label_replace(
            increase(container_cpu_cfs_throttled_periods_total{container!="", container!="POD"}[5m]) * on(pod, namespace) group_left() (kube_pod_status_phase{phase="Running"}==1)
          , "uid", "$1-$2-$3-$4-$5", "id", ".+pod([a-zA-Z0-9]{8})(?:-|_)([a-zA-Z0-9]{4})(?:-|_)([a-zA-Z0-9]{4})(?:-|_)([a-zA-Z0-9]{4})(?:-|_)([a-zA-Z0-9]{12}).+")
        )
  - name: memory
    rules:
    - record: container_memory_working_set_bytes:sum
      expr: |-
        sum by (uid,container,pod,namespace,node) (
          label_replace(
            container_memory_working_set_bytes{container!="", container!="POD"} * on(pod, namespace) group_left() (kube_pod_status_phase{phase="Running"}==1)
          , "uid", "$1-$2-$3-$4-$5", "id", ".+pod([a-zA-Z0-9]{8})(?:-|_)([a-zA-Z0-9]{4})(?:-|_)([a-zA-Z0-9]{4})(?:-|_)([a-zA-Z0-9]{4})(?:-|_)([a-zA-Z0-9]{12}).+")
        )
    - record: kube_pod_container_resource_requests:memory:running
      expr: |-
        sum by (uid,container,pod,namespace,node) (
          kube_pod_container_resource_requests{resource="memory"} * on(pod, namespace) group_left() (kube_pod_status_phase{phase="Running"}==1)
        )
    - record: kube_pod_container_resource_limits:memory:running
      expr: |-
        sum by (uid,container,pod,namespace,node) (
          kube_pod_container_resource_limits{resource="memory"} * on(pod, namespace) group_left() (kube_pod_status_phase{phase="Running"}==1)
        )
  - name: storage
    rules:
    - record: container_fs_reads_bytes_total:sum_rate5m
      expr: |-
        sum by (uid,container,pod,namespace,node) (
          label_replace(
            rate(container_fs_reads_bytes_total{}[5m]) * on(pod, namespace) group_left() (kube_pod_status_phase{phase="Running"}==1)
          , "uid", "$1-$2-$3-$4-$5", "id", ".+pod([a-zA-Z0-9]{8})(?:-|_)([a-zA-Z0-9]{4})(?:-|_)([a-zA-Z0-9]{4})(?:-|_)([a-zA-Z0-9]{4})(?:-|_)([a-zA-Z0-9]{12}).+")
        )
    - record: container_fs_reads_total:sum_rate5m
      expr: |-
        sum by (uid,container,pod,namespace,node) (
          label_replace(
            rate(container_fs_reads_total{}[5m]) * on(pod, namespace) group_left() (kube_pod_status_phase{phase="Running"}==1)
          , "uid", "$1-$2-$3-$4-$5", "id", ".+pod([a-zA-Z0-9]{8})(?:-|_)([a-zA-Z0-9]{4})(?:-|_)([a-zA-Z0-9]{4})(?:-|_)([a-zA-Z0-9]{4})(?:-|_)([a-zA-Z0-9]{12}).+")
        )
    - record: container_fs_writes_bytes_total:sum_rate5m
      expr: |-
        sum by (uid,container,pod,namespace,node) (
          label_replace(
            rate(container_fs_writes_bytes_total{}[5m]) * on(pod, namespace) group_left() (kube_pod_status_phase{phase="Running"}==1)
          , "uid", "$1-$2-$3-$4-$5", "id", ".+pod([a-zA-Z0-9]{8})(?:-|_)([a-zA-Z0-9]{4})(?:-|_)([a-zA-Z0-9]{4})(?:-|_)([a-zA-Z0-9]{4})(?:-|_)([a-zA-Z0-9]{12}).+")
        )
    - record: container_fs_writes_total:sum_rate5m
      expr: |-
        sum by (uid,container,pod,namespace,node) (
          label_replace(
            rate(container_fs_writes_total{}[5m]) * on(pod, namespace) group_left() (kube_pod_status_phase{phase="Running"}==1)
          , "uid", "$1-$2-$3-$4-$5", "id", ".+pod([a-zA-Z0-9]{8})(?:-|_)([a-zA-Z0-9]{4})(?:-|_)([a-zA-Z0-9]{4})(?:-|_)([a-zA-Z0-9]{4})(?:-|_)([a-zA-Z0-9]{12}).+")
        )
  - name: network
    rules:
    - record: container_network_receive_bytes_total:sum_rate5m
      expr: |-
        sum by (pod,namespace,node) (
          rate(container_network_receive_bytes_total[5m]) * on(pod, namespace) group_left() (kube_pod_status_phase{phase="Running"}==1)
        )
    - record: container_network_receive_packets_total:sum_rate5m
      expr: |-
        sum by (pod,namespace,node) (
          rate(container_network_receive_packets_total[5m]) * on(pod, namespace) group_left() (kube_pod_status_phase{phase="Running"}==1)
        )
    - record: container_network_receive_packets_dropped_total:sum_rate5m
      expr: |-
        sum by (pod,namespace,node) (
          rate(container_network_receive_packets_dropped_total[5m]) * on(pod, namespace) group_left() (kube_pod_status_phase{phase="Running"}==1)
        )
    - record: container_network_transmit_bytes_total:sum_rate5m
      expr: |-
        sum by (pod,namespace,node) (
          rate(container_network_transmit_bytes_total[5m]) * on(pod, namespace) group_left() (kube_pod_status_phase{phase="Running"}==1)
        )
    - record: container_network_transmit_packets_total:sum_rate5m
      expr: |-
        sum by (pod,namespace,node) (
          rate(container_network_transmit_packets_total[5m]) * on(pod, namespace) group_left() (kube_pod_status_phase{phase="Running"}==1)
        )
    - record: container_network_transmit_packets_dropped_total:sum_rate5m
      expr: |-
        sum by (pod,namespace,node) (
          rate(container_network_transmit_packets_dropped_total[5m]) * on(pod, namespace) group_left() (kube_pod_status_phase{phase="Running"}==1)
        )